server:
  port: 8888
spring:
  application:
    name: config-server
  profiles:
    active: local
    include:
      - native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config/${spring.profiles.active}
    consul:
      host: localhost
      port: 8500
      discovery:
        instance-id: ${spring.application.name}-${server.port}-${spring.cloud.client.ip-address}
        prefer-ip-address: true
        register: true
        enabled: true

