spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://3.108.178.201:8180/realms/sg_uat
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs
  zipkin:
    base-url: http://3.108.178.201:9411
  sleuth:
    sampler:
      probability: 1.0
  cloud:
    gateway:
      routes[0]:
        id: authentication-service
        uri: lb://authentication-service
        predicates:
          - Path=/api/auth/**
      routes[1]:
        id: customer-service
        uri: lb://customer-service
        predicates:
          - Path=/customer/**
      routes[2]:
        id: marketplace-service
        uri: lb://marketplace-service
        predicates:
          - Path=/marketplace/**

jwt:
  auth:
    converter:
      jti: jti
      email: email
      role: role

portal:
  cloud:
    authentication-service:
      marketplace:
        client-id: marketplace-user
        client-secret: dDFGRWI4eGVlWHk3QCRMXlpRSWlBZGowIzFNQ0FSVWg1cXM0SjkyTWx5OSQ3JDM5Rzk=
      perdix:
        client-id: perdix-user
        client-secret: VXcwSm0hY0VQaWpzbiY3MjF0Q1JVIURPN1VFazJWRjA5SUkkclFWZGVyIUYyU1RKVlI=
      sensei:
        client-id: sensei-user
        client-secret: QDZwNF5RcW40TTBEd1ZLcjg4b2V3MWc3Z0xFcExGa3YqbXNodVFsbmUzZVZiM0NvWkY=
      employee:
        client-id: employee
        client-secret: VVVSYWQwNUdOVkpqVnpRd1ZGUkNSV1F4V2t4amFtYzBZakpXTTAxWFl6TmFNSGhHWTBWNFIyRXpXWEZpV0U1dlpGWkdjMkp0VlhwYVZscHBUVEJPZGxkcldUMD0=

management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

