spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/realms/sg_dev
  cloud:
    gateway:
      routes[0]:
        id: authentication-service
        uri: lb://authentication-service
        predicates:
          - Path=/api/auth/**

portal:
  cloud:
    authentication-service:
      marketplace:
        client-id: marketplace-user
        client-secret: dDFGRWI4eGVlWHk3QCRMXlpRSWlBZGowIzFNQ0FSVWg1cXM0SjkyTWx5OSQ3JDM5Rzk=
      perdix:
        client-id: perdix-user
        client-secret: VXcwSm0hY0VQaWpzbiY3MjF0Q1JVIURPN1VFazJWRjA5SUkkclFWZGVyIUYyU1RKVlI=
      sensei:
        client-id: sensei-user
        client-secret: QDZwNF5RcW40TTBEd1ZLcjg4b2V3MWc3Z0xFcExGa3YqbXNodVFsbmUzZVZiM0NvWkY=
      employee:
        client-id: employee
        client-secret: Y1pjKnpmXjFXRWxXcnY1ZHp3WiRFREMzeXFTKjZlQWJ0VWZnUiNUNGZEUCpeOFNzVUY=

