spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/realms/sg_dev_customer
  cloud:
    gateway:
      routes[0]:
        id: customer-portal
        uri: lb://customer-portal
        predicates:
          - Path=/api/customer-portal/**
      routes[1]:
        id: advance-salary
        uri: lb://advance-salary
        predicates:
          - Path=/api/advance-salary/**

